[package]
name = "rust_playground"
version = "0.1.0"
edition = "2024"

[dependencies]
mysql = "=26.0.1"
tonic = "0.11"
tokio = { version = "1.37", features = ["macros", "rt-multi-thread"] }
prost = "0.12"

[build-dependencies]
tonic-build = "0.11"